### ISSUE TITLE
Error: Request failed with status code 401

### ISSUE THREAD

**Issue by besiwims** [bradtraversy/chatgpt-chatbot#3]
You: hi
Error: Request failed with status code 401
    at createError (/home/wims/chatgpt-chatbot/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/wims/chatgpt-chatbot/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/wims/chatgpt-chatbot/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:525:35)

I have generated an api key

**Comment by vferraz7** [comment]
Hi, you received a unauthorized response from OpenAI API, an incorrect API key was provided.
You can [check your API keys here](https://platform.openai.com/account/api-keys) .
